config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  namespace 'admin' do
    resources :products
    resources :orders
  end

  namespace :api do 
    namespace :v1 do 
      resources :orders do 
        get 'cart', on: :collection, to: 'orders#get_cart'
        put 'update', on: :member
      end
      resources :order_items do
        post 'create', on: :member
      end
      resources :addresses, only: [:create, :update]
      resources :states, only: :index
      resources :credit_cards, only: [:create, :update]
    end
  end

  resources :orders, only: :show
  resources :products, only: [:show, :index]

  get 'cart', to: 'cart#index'
  post 'cart/cart_destroy', to: 'cart#cart_destroy', as: :cart_destroy
  get 'cart/billing', to: 'cart#billing'
  get 'checkout', to: 'checkout#index'
  get 'account', to: 'home#account', as: :account
  get 'orders/:order_id', to: 'orders#show'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end

  def cart_destroy
    cart.state = Order::CANCELLED
    cart.delete

    redirect_to products_path
  end
end

app/helpers/cart_helper.rb
module CartHelper

  def cart
    id = session[:cart_id]
    if id
      order = Order.where(id: id, state: Order::CART).take
    elsif user_signed_in?
      order = current_user.orders.where(state: Order::CART).take
    end

    if order
      order.update(user_id: current_user.id) if !order.user_id and user_signed_in?
      session[:cart_id] = order.id
    end
    order
  end

  def create_cart
    order = Order.create(user_id: current_user.try(:id))
    session[:cart_id] = order.id if order
    order
  end
end

app/views/cart/index.html.haml
.container
  %H3 Your current cart:
  .cart_item{"ng-controller" => "CartController"}
    %table.col-sm-12
      %tr.col-headers
        %th.item
          Item
        %th.quantity
          Update
        %th.quantity
          Quantity
        %th.price
          Item Price
        %th.price
          Price
      %tr{"ng-repeat" => "item in cart.order_items", "ng-controller" => "ItemController"}
        %td.item
          {{item.source.name}}
        %td.quantity
          .form-group
            %select.form-control{"ng-model" => "item.quantity", "ng-change" => "add_product(item)", "ng-options" => "num for num in arr"}
        %td.quantity
          {{item.quantity}}
        %td.price
          {{item.source.price | currency}}
        %td.price
          {{(item.source.price)*(item.quantity) | currency}}
      %tr
        %td.item.total
          Total:
        %td.quantity
          %button
            = link_to 'Update', cart_path
        %td.quantity.total
          {{cart.product_count}}
        %td.price.total
        %td.price.total
          {{total() | currency}}
  .checkout-link
    -if user_signed_in?
      %button.to_checkout
        = link_to 'Checkout', checkout_path
    -else
      %button
        = link_to 'Sign-in to Checkout', new_user_session_path
    %button.empty_cart
      = link_to 'Empty Cart', cart_destroy_path, method: :post
  .bottom_links
    =link_to 'Home', root_path
    |
    =link_to 'Products', products_path