config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  namespace 'admin' do
    resources :products
    resources :orders
  end

  namespace :api do 
    namespace :v1 do 
      resources :orders do 
        get 'cart', on: :collection, to: 'orders#get_cart'
        put 'update', on: :member
      end
      resources :order_items do
        post 'create', on: :member
      end
      resources :addresses, only: [:create, :update]
      resources :states, only: :index
      resources :credit_cards, only: [:create, :update]
    end
  end

  resources :orders, only: :show
  resources :products, only: [:show, :index]

  get 'cart', to: 'cart#index'
  post 'cart/cart_destroy', to: 'cart#cart_destroy', as: :cart_destroy
  get 'cart/billing', to: 'cart#billing'
  get 'checkout', to: 'checkout#index'
  get 'account', to: 'home#account', as: :account
  get 'orders/:order_id', to: 'orders#show'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user, inverse_of: :orders
  has_many :order_items, inverse_of: :order
  belongs_to :address
  has_one :payment

  attr_accessor :credit_card_id

  self.state_machine({
      cart: [:placed],
      placed: [:cancelled],
      cancelled: []
  })

  before_transition_to :placed do

    unless address = user.address
      address.save
    else
      errors[:base] << address.errors.map{|k, v| "Cannot place order with no address. #{k}:  #{v}"}
      return false if errors.present?
    end

    if order_items.to_a.sum{|x| x.quantity} == 0
      errors[:base] << "Cannot place an order with no items."
      return false if errors.present?
    end
    order_items.each do |item|
      if item.source.on_hand >= item.quantity
        puts "#{item.source.name} is good to go."
      else
        errors[:base] << "#{item.source.name} does not have enough available inventory. Only #{item.source.on_hand} left."
        item.update(quantity: item.source.on_hand)
      end
    end

    return false if errors.present?

    order_items.each do |item|
      item.source.on_hand -= item.quantity
      item.source.save
    end

    order_total = order_items.to_a.sum{|x| x.source.price * x.quantity}
    payment = Payment.find_or_initialize_by(credit_card_id: credit_card_id, order_id: id, state: Payment::PENDING)
    payment.amount = order_total
    unless payment.save
      errors[:base] << payment.errors.map{|k, v| "Payment Error #{k}: #{v}"}
    end
    unless payment.make_completed
      errors[:base] << payment.errors.map{|k, v| "Payment Error #{k}: #{v}"}
    end
    errors.empty?

  end

  after_transition_to :placed do
    UserMailer.order_email(self.id).deliver_later if !Rails.env.test?
  end

  def serializable_hash(options={})
    {
      product_count: order_items.where(source_type: Product.name).sum(:quantity),
      order_items: order_items.map(&:serializable_hash)
    }.merge(super(options))
  end

end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminController
    layout "admin/application"

    def index
      @orders = Order.where(state: "placed")
    end

    def show
      @order = Order.find(params[:id])
      @credit = @order.payment.credit_card
    end

    protected

    def order_params
      params.require(:order).permit(:user, :address, :state, :id, :payment)
    end
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  load_and_authorize_resource
  wrap_parameters include: Order.column_names + [:credit_card_id]

  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      render json: {
        message: ["permission denied"]
      }, status: 302
    else
      render json: {
          message: ["Not logged in"]
      }, status: 303
    end
  end

  def get_cart
    if cart
      render json: cart.to_json
    else
      render json: {}, status: 404
    end
  end

  def update
    order = Order.find_or_initialize_by(id: params[:id])
    if order.update(order_params)
      render json: order.to_json, status: 200
    else
      render json: order.errors.to_json, status: 400
    end
  end

  protected
  def order_params
    params.require(:order).permit(:user_id, :address_id, :state, :credit_card_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout "application"

  def show
    @order = Order.find(params[:id])
    @credit = @order.payment.credit_card
  end

  protected
  def order_params
    params.require(:order).permit(:user, :address, :state, :id, :payment)
  end
end

app/views/admin/orders/index.html.haml
%h1 Placed Orders
.container
  %br
  %table.order_table
    %tbody
      %tr.headers
        %th.order_num
          Order number
        %th.cust_name
          Customer Name
        %th.quant
          Item Quantity
        %th.order_total
          Order Total
        %th.view
          Order Details
      - @orders.each do |order|
        %tr.order
          %td.order_num
            = order.id
          %td.name
            = order.address.name
          %td.qty
            = order.order_items.to_a.sum(&:quantity)
          %td.total
            = number_to_currency order.payment.amount
          %td.view
            = link_to 'View Order', admin_order_path(order.id)

  %br
  %br
  .bottom_links
    = link_to 'Admin Product Page', admin_products_path

app/views/admin/orders/show.html.haml
%h1 Order completed
.container
  .address_box.col-sm-4
    %h3.checkout_label
      Address
    %table
      %tbody.address_block
        %tr
          %td
            %label.check_address
              Name
          %td
            .address_input
              = @order.address.name
        %tr
          %td
            %label.check_address
              Line 1
          %td
            .address_input
              = @order.address.line1
        %tr
          %td
            %label.check_address
              Line 2
          %td
            .address_input
              = @order.address.line2
        %tr
          %td
            %label.check_address
              City
          %td
            .address_input
              = @order.address.city
        %tr
          %td
            %label.check_address
              State
          %td
            .address_input
              = @order.address.state.name
        %tr
          %td
            %label.check_address
              Zipcode
          %td
            .address_input
              = @order.address.zip
  .billing_box.col-sm-4
    %h3.checkout_label
      Billing
    %table
      %tbody.cc_block
        %tr
          %td
            %label.check_cc
              Name on card
          %td
            .address_input
              = @credit.name
        %tr
          %td
            %label.check_cc
              Credit Card Number
          %td
            .address_input
              = "XXXXXXXXXXXX#{@credit.last_four}"
        %tr
          %td
            %label.check_cc
              Expiration month
          %td
            .address_input
              = @credit.month
        %tr
          %td
            %label.check_cc
              Expiration year
          %td
            .address_input
              =@credit.year
        %tr
          %td
            %label.check_cc
              CVC
          %td
            .address_input
              XXX
  .cart_box.col-sm-4
    %h3.checkout_label
      Order Items
    %table
      %tr.col-headers
        %th.item
          Item
        %th.quantity
          Quantity
        %th.price
          Price
      - @order.order_items.each do |item|
        %tr
          %td.item
            = item.source.name
          %td.quantity
            = item.quantity
          %td.price
            = number_to_currency (item.source.price*item.quantity)
      %tr
        %td.item.total
          Total:
        %td.quantity.total
          = @order.order_items.to_a.sum(&:quantity)
        %td.price.total
          = number_to_currency @order.order_items.to_a.sum{|x| x.source.price*x.quantity}


  .bottom_links
    = link_to 'Admin Product Page', admin_products_path
    |
    = link_to 'Admin Orders', admin_orders_path