config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  namespace 'admin' do
    resources :products
    resources :orders
  end

  namespace :api do 
    namespace :v1 do 
      resources :orders do 
        get 'cart', on: :collection, to: 'orders#get_cart'
        put 'update', on: :member
      end
      resources :order_items do
        post 'create', on: :member
      end
      resources :addresses, only: [:create, :update]
      resources :states, only: :index
      resources :credit_cards, only: [:create, :update]
    end
  end

  resources :orders, only: :show
  resources :products, only: [:show, :index]

  get 'cart', to: 'cart#index'
  post 'cart/cart_destroy', to: 'cart#cart_destroy', as: :cart_destroy
  get 'cart/billing', to: 'cart#billing'
  get 'checkout', to: 'checkout#index'
  get 'account', to: 'home#account', as: :account
  get 'orders/:order_id', to: 'orders#show'
end

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %title Mike's Ice Cream Tree's
    = stylesheet_link_tag    'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'
    = javascript_include_tag 'application'
    %link{:href => 'https://fonts.googleapis.com/css?family=Nosifer', :rel => "stylesheet", :type => "text/css"}/
    = csrf_meta_tags
  %body{"ng-app" => "treeApp", class: "#{action_name} #{controller_name}", 'ng-controller' => 'BodyController'}
    .top-buttons
      .btn-group
        %button.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          Account
          %span.caret
        %ul.dropdown-menu
          %li= link_to 'Login', new_user_session_path
          %li= link_to 'Sign-up', new_user_registration_path
          %li= link_to 'Sign out', destroy_user_session_path
          -if user_signed_in?
            %li= link_to 'Account details', account_path
            -if current_user.is_admin?
              %li= link_to 'Admin Products', admin_products_path
              %li= link_to 'Admin Orders', admin_orders_path
      .cart_thing
        =link_to cart_path, class: "cart pull-right" do
          Cart
          %span.badge{"ng-model" => "cart.product_count"}
            ({{cart.product_count}})
    .header
      .bgImage
        .name= link_to "Michael's Ice Cream Trees", root_path
    - flash.each do |name, msg|
      = content_tag :div, msg, class: name
    .page_content
      = yield