config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  namespace 'admin' do
    resources :products
    resources :orders
  end

  namespace :api do 
    namespace :v1 do 
      resources :orders do 
        get 'cart', on: :collection, to: 'orders#get_cart'
        put 'update', on: :member
      end
      resources :order_items do
        post 'create', on: :member
      end
      resources :addresses, only: [:create, :update]
      resources :states, only: :index
      resources :credit_cards, only: [:create, :update]
    end
  end

  resources :orders, only: :show
  resources :products, only: [:show, :index]

  get 'cart', to: 'cart#index'
  post 'cart/cart_destroy', to: 'cart#cart_destroy', as: :cart_destroy
  get 'cart/billing', to: 'cart#billing'
  get 'checkout', to: 'checkout#index'
  get 'account', to: 'home#account', as: :account
  get 'orders/:order_id', to: 'orders#show'
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :permalink
  has_many :order_items, as: :source

  before_create :set_permalink

  def formatted_image
    @image = "products/" + image.split("/").last
    ActionController::Base.helpers.image_url(@image.to_str)
  end

  def formatted_link
    "localhost:3000/products/" + permalink.to_s
  end

  def serializable_hash(options={})
    {
      formatted_image: formatted_image,
      formatted_link: formatted_link
    }.merge(super(options))
  end

  def set_permalink
    self.permalink = self.name.parameterize
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminController
    load_resource find_by: :permalink
    authorize_resource

    def index
    end

    def show
    end

    def new
      @images = Dir.glob("app/assets/images/products/*.jpg")
    end

    def edit
      @images = Dir.glob("app/assets/images/products/*.jpg")
    end

    def create
      @product = Product.new(product_params)
      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_products_url, notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :permalink, :on_hand, :available, :price, :description, :image)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "application"
  before_action :set_product, only: [:show]

  def index
    @products = Product.where(available: true)
  end

  def show
    @product ||= Product.find_by_id(params[:id])
  end

  private
    def set_product
      @product = Product.find_by_permalink(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :permalink, :on_hand, :available, :price, :description, :image)
    end
end

app/views/admin/products/_form.html.haml
- if @product.errors.any?
  #error_explanation
    %h2
      = pluralize(@product.errors.count, "error")
      prohibited this product from being saved:
    %ul
      - @product.errors.full_messages.each do |message|
        %li= message
.actions
.col-sm-12
  .col-sm-3.form_label
    =f.label :name
    %br
    =f.text_field :name
  .col-sm-3.form_label
    =f.label :on_hand
    %br
    =f.text_field :on_hand
  .col-sm-3.form_label
    =f.label "Available (check for yes)"
    %br
    =f.check_box :available
  .col-sm-3.form_label
    =f.label :price
    %br
    =f.text_field :price


  .img_admin
    =f.label :image
    =f.select :image, options: @images
  .description
    =f.label :description
    %br
    =f.text_area :description
    %br
  .submit
    =f.submit

app/views/admin/products/edit.html.haml
%h1 Editing Product
.container
  = form_for(@product, url: admin_product_path(@product.permalink)) do |f|
    = render partial: 'form', locals: {f: f}
    .bottom_links
      = link_to 'Show', admin_product_path
      |
      = link_to 'Back', admin_products_path

app/views/admin/products/index.html.haml
%p#notice= notice
.container
  %h1 Listing Products
  %br
  %table
    %tbody
      - @products.each do |product|
        %tr
          %td.product_name
            = product.name
          %td.admin_link
            = link_to 'Destroy', admin_product_path(product.permalink), method: :delete, data: { confirm: 'Are you sure?' }
          %td.admin_link
            = link_to 'Edit', edit_admin_product_path(product.permalink)
          %td.admin_link
            = link_to 'View', admin_product_path(product.permalink)

  %br
  %br
  .bottom_links
    = link_to 'New Product', new_admin_product_path
    |
    = link_to 'Customer View', products_path
    |
    =link_to 'Orders', admin_orders_path

app/views/admin/products/new.html.haml
%h1 New Product
.container
  = form_for(@product, url: admin_products_path) do |f|
    = render partial: 'form', locals: {f: f}
    .bottom_links
      = link_to 'Back', admin_products_path

app/views/admin/products/show.html.haml
%p#notice= notice
.container
  %p
    %strong
      Product Name:
    = @product.name
  .image_box
    = image_tag "products/#{@product.image.split('/').last}"
  %p
    %strong
      Product permalink:
    = @product.permalink
  %p
    %strong
      Quantity on hand:
    = @product.on_hand
  %p
    %strong
      Available:
    -if @product.available?
      Yes
    -else
      No
  %p
    %strong
      Price:
    = @product.price
  %p
    %strong
      Description:
    = @product.description

.bottom_links
  = link_to 'Edit', edit_admin_product_path(@product.permalink)
  |
  = link_to 'Back', admin_products_path
  |
  = link_to 'Customer View', product_path(@product.permalink)